export const navItems = [
  { href: 'index.html', text: '<img src="images/logo.png" alt="logo">' },
  { href: 'index.html', text: 'Home' },
  { href: 'projects.html', text: 'Projecten' },
  { href: 'contact.html', text: 'Contact' },
];

export const projects = [
  {
    id: 1,
    category: 'HTML/CSS/JS',
    title: 'iLeren',
    image: 'ileren.png',
    link: 'https://ileren.be/',
    summary: 'Edutools en online apps',
    details: '',
  },
  {
    id: 2,
    category: 'HTML/CSS/JS',
    title: 'Schuilplaats',
    image: 'schuilplaats.png',
    link: 'https://schuilplaats.be/',
    summary: 'Muziekstreaming',
    details: '',
  },
  {
    id: 3,
    category: 'HTML/CSS/JS',
    title: 'Grammatica',
    image: 'nt2grammatica.png',
    link: 'https://cvogent.be/nt2grammatica',
    summary: 'Grammatica voor anderstaligen',
    details: '',
  },
  {
    id: 4,
    category: 'HTML/CSS/JS',
    title: 'Digiboek',
    image: 'nt2digiboek.png',
    link: 'https://dirkb.be/portfolio/nt2digiboek-sample/',
    summary: 'Online handboeken',
    details: '',
  },
  {
    id: 5,
    category: 'PHP & SQL',
    title: 'Mimosa',
    image: 'mimosa.png',
    link: 'https://dirkb.be/mimosa',
    summary: 'Fotogallerij',
    details: 'Farmstand',
  },
  {
    id: 6,
    category: 'PHP & SQL',
    title: 'Farmstand',
    image: 'farmstand.png',
    link: 'https://dirkb.be/farmstand',
    summary: 'Oefenproject met eigen MVC-framework.',
    details: '',
  },
  {
    id: 7,
    category: 'PHP & SQL',
    title: 'CVO Voeding',
    image: 'bestellingen-voeding.png',
    link: 'https://cvogent.be/bestellingen-voeding',
    summary: 'Oefenproject met eigen MVC-framework.',
    details: '',
  },
  {
    id: 8,
    category: 'PHP & SQL',
    title: 'CVO BIB',
    image: 'cvobib.png',
    link: 'https://cvogent.be/cvobib/',
    summary: 'Bibliotheekapplicatie',
    details: '',
  },
  {
    id: 9,
    category: 'Android Apps',
    title: 'NT2<br>Grammatica',
    image: 'nt2grammatica-android.png',
    link: 'https://play.google.com/store/apps/details?id=be.ileren.grammatica',
    summary: 'Grammatica voor anderstaligen',
    details: '',
  },
  {
    id: 10,
    category: 'Android Apps',
    title: 'NT2<br>Werkwoorden',
    image: 'nt2werkwoorden.png',
    link: 'https://play.google.com/store/apps/details?id=be.ileren.werkwoorden',
    summary: 'Studeer onregelmatige werkwoorden',
    details: '',
  },
  {
    id: 11,
    category: 'Android Apps',
    title: 'NT2<br>Voorzetsels',
    image: 'nt2voorzetsels.png',
    link: 'https://play.google.com/store/apps/details?id=be.ileren.voorzetsels',
    summary: 'Studeer voorzetsels',
    details: '',
  },
  {
    id: 12,
    category: 'Android Apps',
    title: 'NT2<br>Eten en Drinken',
    image: 'nt2etenendrinken.png',
    link: 'https://play.google.com/store/apps/details?id=ileren.be.nt2etenendrinken',
    summary: 'Studeer woordenschat',
    details: '',
  },
  {
    id: 13,
    category: 'Android Apps',
    title: 'Medisch Rekenen',
    image: 'medischrekenen.png',
    link: 'https://play.google.com/store/apps/details?id=appinventor.ai_diboma.MedischRekenen',
    summary: 'Maak medische berekeningen',
    details: '',
  },
  {
    id: 14,
    category: 'Android Apps',
    title: 'Zuur-Base Lijst',
    image: 'zuurbase.png',
    link: 'https://play.google.com/store/apps/details?id=be.ileren.zuurbase',
    summary: 'Voedingslijst met zuur-base waarden',
    details: '',
  },
  {
    id: 15,
    category: 'Cloud Installaties',
    title: 'Canvas LMS',
    image: 'canvas.png',
    link: 'https://canvas.dirkb.cyou/',
    summary: 'Testomgeving',
    details: '',
  },
  {
    id: 16,
    category: 'Cloud Installaties',
    title: 'Just Do IT',
    image: 'justdoit.png',
    link: 'https://gcp.dirkb.cyou:3000/',
    summary: 'Todo applicatie',
    details: '',
  },
];
